[package]
name = "abacus"
version = "0.1.0"
authors = ["ictxiangxin <ictxiangxin@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
name = "abacus"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
